### ISSUE TITLE
do we improve routes using yml?

### ISSUE THREAD

**Issue by marcuxyz** [marcuxyz/mvc_flask#7]
What do you think about changing the definition of routes from json to yaml? 

Something like: 

```yml
routes:
  home:
    index
  
  books:
    new:
      path: /
    create:
      path: /create
      method: post
  
  posts:
    models: true
    only:
      - show
      - new
      - create
  
  users:
    index:
      hooks:
        before_request: "required"
```

if the user define `model: true` the `mvc-flask` automatically will be create the follows routes:

```
- index (/)
- show (/show/:id)
- new (/new)
- create (/create)
- edit (/edit/:id)
- update (/)
- delete (/delete/:id)
```

But, you can use the `only` parameter to regular this.
